### ISSUE TITLE
Number Validation is strange

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#20]
## Specs
We should accept **values >=0** of **.25 increments**. 

(I can see a good use for 0hr entries -- useful for notes)

## Firefox seems to be the most buggy here

![image](https://user-images.githubusercontent.com/1143370/46307203-8a7a9380-c573-11e8-8d8b-417abb851373.png)

There should be no extra characters or anything in that field. This happened several times via casual use. It may follow an invalid number submission and simply not catch up.

## But Chrome also will throw the odd error too

![image](https://user-images.githubusercontent.com/1143370/46307380-01179100-c574-11e8-89b7-524b05e6b487.png)

(I was trying to break Chrome at this point)

**Comment by simmeringc** [comment]
Number validation on all hour input forms (time entry new form, time entry edit modal, time entry create and submit form) now require a number greater than or equal to zero and less than 100 and all step by 0.25
