### ISSUE TITLE
Need ability to close hourlog with submitted entries

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#22]
This scenario comes up quite a bit. 
Say contractor submits hours the week which include 9/30 & 10/1 ...

I will adjudicate the 9/30 entry and close out the a September hourlog

The 10/1 entry should then be left in the "submitted" state and just moved to the new current hourlog for that company

**Comment by simmeringc** [comment]
Added the ability to close hour logs with submitted time entries, moving the submitted time entries to a new Current hour log. Only an open hour log can have one or many submitted time entries, same as before.
