### ISSUE TITLE
Can't Reopen (some) Hourlogs

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#24]
https://dd9app-staging.herokuapp.com/company/100100000000000000000000

I tried re-opening several of these legacy hourlogs on "Complete Intelligence".

We will need to fix the bug blocking me from **_closing_** some of the legacy hourlogs. It is probably less important that I can reopen those old ones, though the bugs are probably related

**Comment by simmeringc** [comment]
Fixed the legacy open-close hour log bug. All hour logs from any company can now be open and closed. Open hour logs merge with or become the current hour log as per usual.
