### ISSUE TITLE
Need "Export View" on Hourlog

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#25]
At billing, I often just past the hourlog contents right into a line item entry on the invoice.

Because the target is just a free text field, we want a stripped down and abbreviated version of the published public hourlog, like this

`mm-dd` `lastname` `hrs` `description`

(image removed)

**Comment by simmeringc** [comment]
Added an export timeEntry modal to closed hourLogs. Let me know what kind of copy paste formatting you need or if it doesn't matter.

![screen shot 2018-10-14 at 7 38 55 pm](https://user-images.githubusercontent.com/10622438/46925634-17990000-cfea-11e8-8728-f34e45a51153.png)
![screen shot 2018-10-14 at 7 38 59 pm](https://user-images.githubusercontent.com/10622438/46925635-17990000-cfea-11e8-991a-cd8c230bcd64.png)
![screen shot 2018-10-14 at 7 44 13 pm](https://user-images.githubusercontent.com/10622438/46925636-17990000-cfea-11e8-8c4b-094e78b44d68.png)
