### ISSUE TITLE
Need to be able to edit closed hour_log titles

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#26]
This does come up occasionally. I would not want to have to reopen an hour_log(risk mixing up the time entries) just to fix a type-o in the hour_log name.

Right now, we have in-place editing for the hour_log titles, though obviously this can be a modal on the new system.

![image](https://user-images.githubusercontent.com/1143370/46328437-65fad780-c5c4-11e8-9938-555ad3a770db.png)

**Comment by simmeringc** [comment]
Added edit hour log functionality to closed hour logs. Hour logs cannot be renamed to 'current'.
