### ISSUE TITLE
Sort by hour_log Title not working

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#27]
This might be one of the known bugs.

The only place this would be really useful would be on the open hour_logs so I could cluster all the hour_logs with pending time_entries for adjudication

![image](https://user-images.githubusercontent.com/1143370/46328476-a6f2ec00-c5c4-11e8-942d-a780e2efaff7.png)

**Comment by simmeringc** [comment]
Fixed open company hour_logs table sorting errors. Fixed multiple table sorting errors in other tables as well.
