### ISSUE TITLE
Disable Auto-complete / Auto-suggestions on Date Field

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#32]
This is annoying

![image](https://user-images.githubusercontent.com/1143370/48042029-0b154c80-e13d-11e8-81a6-a43c3607fcae.png)

I realize this is a browser thing, but the legacy site doesn't have auto complete here, and we definitely don't want it

**Comment by simmeringc** [comment]
Turned autoComplete off on all form fields site wide. Fixed ReadOnly prop for datepicker fields.
