### ISSUE TITLE
Can't Close Hourlog

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#34]
I think this is bugged across the board, or at least all hourlogs with legacy data

/companyHourLogs/5bdf51fe902fcd629dfea4f6

/companyHourLogs/5bdf51fd902fcd629dfea4f3

![image](https://user-images.githubusercontent.com/1143370/48042293-38162f00-e13e-11e8-8d7f-2b3a011ff9ff.png)

**Comment by simmeringc** [comment]
Fixed
