### ISSUE TITLE
Closing Contractor Hour Log Should Submit time entries, right?

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#36]
![image](https://user-images.githubusercontent.com/1143370/48044623-16bb4000-e14a-11e8-9afb-db5d10ca1de3.png)

I realize I could submit, then close. But seems like close should just take care of that.

**Comment by simmeringc** [comment]
I think you should deliberately submit all and then close to separate concerns. This is another one we should revisit after using the system in production for a little.
