### ISSUE TITLE
Contractor Time Entries Should be Editable by Admin

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#37]
![image](https://user-images.githubusercontent.com/1143370/48044688-7580b980-e14a-11e8-9fec-24d0b5fccee0.png)

This is a feature I will need, just ran into a scenario where I needed to fix something for billing today.

From this UI, admin should be editing original data, not public data

**Comment by simmeringc** [comment]
Implemented original timeEntry editing for admins, staff, and contractors on contractor hour logs.
