### ISSUE TITLE
Adjudicated Time Entries Disappear (temporarily)

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#39]
Step 1: Make some edits, then save
![image](https://user-images.githubusercontent.com/1143370/48045111-2f2c5a00-e14c-11e8-9e89-0142126371d7.png)

Step 2: Entry is gone (at least temporarily)

![image](https://user-images.githubusercontent.com/1143370/48045162-67cc3380-e14c-11e8-95ae-fd5501836c10.png)

--
Reload will show adjudicated entries

**Comment by simmeringc** [comment]
Fixed bug in companyHourLog reducer. Adjudications that include changing the company of a timeEntry still remove the timeEntry from the companyHourLog in real-time.
