### ISSUE TITLE
Can't Reactivate Company

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#42]
![image](https://user-images.githubusercontent.com/1143370/48045685-99de9500-e14e-11e8-9679-8629ed966171.png)

Didn't work for any I tried. Could be a legacy company thing, haven't tested with new company yet

**Comment by todditron** [comment]
Can deactivate a new company either

**Comment by simmeringc** [comment]
Fixed issue where modal's wouldn't submit their forms on initial component mount.
