### ISSUE TITLE
Only Admins can see adjudicated data

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#44]
Employees & Contractors should *not* be able to see this information

![image](https://user-images.githubusercontent.com/1143370/49120094-924f6f00-f268-11e8-9bc8-11e8c5e49744.png)

**Comment by simmeringc** [comment]
Only admins can request and see adjudicated data in contractorHourLog timeEntry data dropdowns. Employees and Contractors can still see the altered status (submitted -> approved) of a timeEntry in the JSON request as the page needs it to sort the tables, the alternative is a public and original status's.
